package com.niro.modules.audit.domain;

public enum AuditEventType {
    USER_REGISTERED,
    EMAIL_VERIFIED,
    USER_LOGGED_IN,
    DATASET_GENERATED,
    RISK_SCAN_STARTED,
    RISK_SIGNAL_DETECTED,
    RISK_ASSESSMENT_CREATED,
    CLUSTER_IDENTIFIED,
    INVESTIGATION_CREATED,
    INVESTIGATION_STATUS_CHANGED,
    NOTE_ADDED,
    AI_ASSESSMENT_GENERATED,
    DECISION_RECOMMENDED,
    EVALUATION_COMPLETED,
    INVESTIGATION_RESOLVED
}
