"""
IEEE-CIS feature builder for inference time.

At training time we had raw CSV columns (card1, card2, C1-C14, D1-D15, V-cols, etc.).
At inference time Spring Boot sends a PredictRequest with the canonical Zeno fields
(amount, timestamp, payment_method, email_domain, device_id, customer_context, etc.).

This module maps from the PredictRequest / CustomerContextPayload to the exact same
119-feature vector the XGBoost model was trained on.

Features that were computed from raw IEEE-CIS-specific columns and cannot be
reconstructed at inference time (card1/card2/card3/card5, C-cols, D-cols, V-cols,
addr1/addr2, dist1/dist2, identity cols) are filled with -1 (the same sentinel
used during training for missing values).

Features that CAN be reconstructed from the canonical request:
  - amount, log_amount, amount_cents_frac, amount_round
  - hour_of_day, day_of_week, is_weekend, is_night
  - product_enc  (from merchant_category)
  - card4_enc    (from payment_method)
  - card6_enc    (from payment_method — mapped to credit/debit heuristic)
  - p_email_risky, p_email_safe, p_email_missing
  - email_match  (always 1 if only one email provided)
  - has_device   (from device_id presence)
  - card1_tx_count (from historical_transaction_count context)

All other features default to -1 (not 0, to match training sentinel).

IMPORTANT: the model was trained with StandardScaler applied to ALL features.
The scaler is loaded from the artefact and applied here too.
"""

from __future__ import annotations

import logging
from datetime import datetime

import numpy as np

logger = logging.getLogger(__name__)

# ── Encoding maps (must match train_ieee_cis.py exactly) ─────────────────

_RISKY_EMAIL_DOMAINS = {
    "anonymous.com", "scranton.edu", "protonmail.com", "mail.com",
    "outlook.es", "aim.com", "frontiernet.net",
}
_SAFE_EMAIL_DOMAINS = {
    "gmail.com", "yahoo.com", "outlook.com", "hotmail.com",
    "icloud.com", "live.com",
}

_PRODUCT_MAP = {
    "DIGITAL_GOODS": 0, "W": 0,
    "APPAREL": 1,       "H": 1,
    "ELECTRONICS": 2,   "C": 2,
    "MARKETPLACE": 3,   "S": 3, "R": 4,
    "TRAVEL": 4, "GROCERY": 5, "GAMING": 6, "FINANCIAL": 7,
}

# payment_method → card4_enc (card network proxy)
_CARD4_MAP = {
    "CARD": 1,
    "WALLET": 3,
    "BANK_TRANSFER": 2,
    "CRYPTO": 4,
    "UNKNOWN": 0,
}

# payment_method → card6_enc (credit=1 / debit=2 heuristic)
_CARD6_MAP = {
    "CARD": 1,       # assume credit by default
    "WALLET": 2,     # debit-like
    "BANK_TRANSFER": 2,
    "CRYPTO": 0,
    "UNKNOWN": 0,
}

# V-column names in training order
_V_COLS = [
    "V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9", "V10",
    "V12", "V13", "V14", "V17", "V19", "V20",
    "V29", "V30",
    "V33", "V34", "V35", "V36", "V37", "V38",
    "V45", "V53", "V54", "V56",
    "V61", "V62", "V70",
    "V75", "V76", "V78", "V80", "V82", "V83",
    "V91", "V94",
    "V96", "V99", "V100",
    "V126", "V127", "V128", "V129", "V130",
    "V133", "V137",
]

_IDENTITY_COLS = [
    "id_01", "id_02", "id_03", "id_04", "id_05", "id_06",
    "id_09", "id_10", "id_11", "id_17", "id_19", "id_20",
]

# Full ordered feature list — must match training output of engineer_features()
# Generated by: list(feats.keys()) in train_ieee_cis.py
# Canonical order is:
#  amount, log_amount, amount_cents_frac, amount_round,
#  hour_of_day, day_of_week, is_weekend, is_night,
#  product_enc,
#  card1, card2, card3, card5, card4_enc, card6_enc,
#  addr1, addr2, addr_mismatch,
#  dist1, dist2, has_dist1,
#  p_email_risky, p_email_safe, r_email_risky, email_match, p_email_missing,
#  C1..C14,
#  D1, D2, D3, D4, D10, D15,
#  M1_enc..M9_enc,
#  card1_tx_count,
#  id_01..id_20, device_type_enc, has_device,
#  V1..V137 subset

SENTINEL = -1.0   # fill for unavailable features (matches training)


def build_feature_vector(
    amount: float,
    timestamp: datetime,
    payment_method: str,
    merchant_category: str,
    email_domain: str | None,
    device_id: str | None,
    historical_tx_count: int,
    feature_names: list[str],
    scaler,
) -> np.ndarray:
    """
    Build a 1-row feature matrix from a PredictRequest, compatible with
    the IEEE-CIS trained XGBoost model.

    Parameters
    ----------
    amount              : transaction amount
    timestamp           : transaction datetime (UTC)
    payment_method      : canonical payment method string
    merchant_category   : canonical merchant category string
    email_domain        : payer email domain (or None)
    device_id           : device fingerprint (or None)
    historical_tx_count : from CustomerContextPayload
    feature_names       : ordered list from metadata.pkl
    scaler              : fitted StandardScaler from scaler.pkl

    Returns
    -------
    X : np.ndarray shape (1, n_features), float32, scaled
    """
    feats: dict[str, float] = {}

    # ── Amount ────────────────────────────────────────────────────────
    amt = max(0.0, float(amount))
    feats["amount"]            = amt
    feats["log_amount"]        = float(np.log1p(amt))
    feats["amount_cents_frac"] = amt % 1.0
    feats["amount_round"]      = 1.0 if (amt % 1.0 == 0.0) else 0.0

    # ── Time ──────────────────────────────────────────────────────────
    hour = float(timestamp.hour)
    dow  = float(timestamp.weekday())  # 0=Mon … 6=Sun
    feats["hour_of_day"] = hour
    feats["day_of_week"]  = dow
    feats["is_weekend"]   = 1.0 if dow >= 5 else 0.0
    feats["is_night"]     = 1.0 if (hour >= 0 and hour < 6) else 0.0

    # ── Product ───────────────────────────────────────────────────────
    feats["product_enc"] = float(_PRODUCT_MAP.get(
        (merchant_category or "UNKNOWN").upper(), 0
    ))

    # ── Card ──────────────────────────────────────────────────────────
    # card1-card3-card5 are numeric card hashes — not available at inference
    feats["card1"] = SENTINEL
    feats["card2"] = SENTINEL
    feats["card3"] = SENTINEL
    feats["card5"] = SENTINEL
    pm = (payment_method or "UNKNOWN").upper()
    feats["card4_enc"] = float(_CARD4_MAP.get(pm, 0))
    feats["card6_enc"] = float(_CARD6_MAP.get(pm, 0))

    # ── Address ───────────────────────────────────────────────────────
    feats["addr1"]        = SENTINEL
    feats["addr2"]        = SENTINEL
    feats["addr_mismatch"] = 0.0   # unknown → assume no mismatch

    # ── Distance ─────────────────────────────────────────────────────
    feats["dist1"]    = 0.0
    feats["dist2"]    = 0.0
    feats["has_dist1"] = 0.0

    # ── Email ─────────────────────────────────────────────────────────
    ed = (email_domain or "").lower().strip()
    feats["p_email_risky"]   = 1.0 if ed in _RISKY_EMAIL_DOMAINS else 0.0
    feats["p_email_safe"]    = 1.0 if ed in _SAFE_EMAIL_DOMAINS  else 0.0
    feats["r_email_risky"]   = feats["p_email_risky"]   # only one domain at inference
    feats["email_match"]     = 1.0   # assume match (single domain)
    feats["p_email_missing"] = 1.0 if not ed else 0.0

    # ── C-columns (card-level aggregates from processor — not available) ─
    for c in [f"C{i}" for i in range(1, 15)]:
        feats[c] = SENTINEL

    # ── D-columns (time delta features — not available) ───────────────
    for d in ["D1", "D2", "D3", "D4", "D10", "D15"]:
        feats[d] = SENTINEL

    # ── M-columns (match flags — not available) ───────────────────────
    for m in [f"M{i}_enc" for i in range(1, 10)]:
        feats[m] = SENTINEL

    # ── card1_tx_count ────────────────────────────────────────────────
    # Proxy: use historical_transaction_count from customer context
    feats["card1_tx_count"] = float(np.log1p(max(0, historical_tx_count)))

    # ── Identity columns ──────────────────────────────────────────────
    for id_col in _IDENTITY_COLS:
        feats[id_col] = SENTINEL

    feats["device_type_enc"] = SENTINEL
    feats["has_device"]      = 1.0 if device_id else 0.0

    # ── V-columns ────────────────────────────────────────────────────
    for v in _V_COLS:
        feats[v] = SENTINEL

    # ── Assemble in the exact column order from training ─────────────
    # Use feature_names from metadata to guarantee column order
    row = np.array(
        [feats.get(name, SENTINEL) for name in feature_names],
        dtype=np.float32,
    ).reshape(1, -1)

    # Apply scaler (fitted on training data)
    if scaler is not None:
        row = scaler.transform(row)

    return row.astype(np.float32)
