package com.zeno.modules.customer.interfaces.dto;

import com.zeno.modules.intelligence.domain.AiAssessmentEntity;
import com.zeno.modules.intelligence.domain.AssessmentType;
import com.zeno.modules.ml.domain.MlPrediction;
import com.zeno.modules.risk.domain.RiskAssessment;
import com.zeno.modules.risk.domain.RiskLevel;
import com.zeno.modules.risk.domain.RiskSignalEntity;

import java.time.Instant;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Combined customer risk detail response for the investigation UI.
 *
 * Contains:
 *   - risk score + level + signals (always available after risk analysis)
 *   - ML prediction + SHAP (when ML service was enabled)
 *   - latest AI assessment (when generated by analyst)
 *   - graph/cluster membership (when cluster detection has run)
 */
public record CustomerRiskDetailResponse(
        UUID assessmentId,
        UUID customerId,
        int riskScore,
        RiskLevel riskLevel,
        boolean flagged,
        List<RiskSignalSummary> signals,

        // ML fields — null when ML service not run
        Double fraudProbability,
        Double anomalyScore,
        String modelVersion,
        List<ShapContribution> shapContributions,

        // AI assessment — null when not yet generated
        AiAssessmentSummary aiAssessment,

        Instant createdAt
) {

    // ── Nested records ────────────────────────────────────────────────────

    public record RiskSignalSummary(
            String signalType,
            String severity,
            double observedValue,
            double baselineValue,
            int scoreContribution,
            String explanation
    ) {}

    public record ShapContribution(
            String feature,
            double shapValue,
            String direction,
            int rank
    ) {}

    public record AiAssessmentSummary(
            UUID id,
            AssessmentType assessmentType,
            double confidence,
            String recommendedAction,
            String provider,
            boolean aiGenerated,
            AiAssessmentEntity.StructuredResult structuredResult,
            String disclaimer,
            Instant createdAt
    ) {}

    // ── Factory ───────────────────────────────────────────────────────────

    public static CustomerRiskDetailResponse from(
            RiskAssessment assessment,
            List<RiskSignalEntity> signals,
            MlPrediction mlPrediction,
            AiAssessmentEntity aiAssessment
    ) {
        List<RiskSignalSummary> signalSummaries = signals.stream()
                .map(s -> new RiskSignalSummary(
                        s.getSignalType().name(),
                        s.getSeverity().name(),
                        s.getObservedValue() != null ? s.getObservedValue() : 0.0,
                        s.getBaselineValue() != null ? s.getBaselineValue() : 0.0,
                        s.getScoreContribution(),
                        s.getExplanation()))
                .collect(Collectors.toList());

        // SHAP from ML prediction
        List<ShapContribution> shap = null;
        if (mlPrediction != null && mlPrediction.getFeatureContributions() != null) {
            shap = mlPrediction.getFeatureContributions().stream()
                    .sorted((a, b) -> Integer.compare(a.rank(), b.rank()))
                    .limit(8)
                    .map(fc -> new ShapContribution(
                            fc.feature(), fc.shapValue(), fc.direction(), fc.rank()))
                    .collect(Collectors.toList());
        }

        // AI assessment summary
        AiAssessmentSummary aiSummary = null;
        if (aiAssessment != null) {
            boolean aiGenerated = aiAssessment.getStructuredResult() != null
                    && Boolean.TRUE.equals(aiAssessment.getStructuredResult().isAiGenerated());
            aiSummary = new AiAssessmentSummary(
                    aiAssessment.getId(),
                    aiAssessment.getAssessmentType(),
                    aiAssessment.getConfidence() != null ? aiAssessment.getConfidence() : 0.0,
                    aiAssessment.getRecommendedAction(),
                    aiAssessment.getProvider(),
                    aiGenerated,
                    aiAssessment.getStructuredResult(),
                    "AI-generated evidence summary. Requires analyst verification. " +
                    "Does not independently establish fraud.",
                    aiAssessment.getCreatedAt()
            );
        }

        return new CustomerRiskDetailResponse(
                assessment.getId(),
                assessment.getCustomerId(),
                assessment.getRiskScore(),
                assessment.getRiskLevel(),
                assessment.isFlagged(),
                signalSummaries,
                assessment.getFraudProbability(),
                assessment.getAnomalyScore(),
                assessment.getModelVersion(),
                shap,
                aiSummary,
                assessment.getCreatedAt()
        );
    }
}
