"""
Canonical transaction and customer schema for the Niro ML pipeline.

Design principles:
- Independent of any source dataset (IEEE-CIS, synthetic, future API).
- Source fields: copied directly from ingestion.
- Derived fields: computed during normalization/feature engineering.
- Synthetic fields: generated from assumptions (e.g. merchant category defaults).
- Missing values are explicit Optional[T] = None, never silently coerced.

Every prediction request, batch job, and training sample is normalized into
RawTransaction before entering the feature pipeline.  Customer context is
supplied separately as CustomerContext and merged during feature computation.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, field_validator, model_validator


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class PaymentMethod(str, Enum):
    CARD         = "CARD"
    BANK_TRANSFER= "BANK_TRANSFER"
    WALLET       = "WALLET"
    CRYPTO       = "CRYPTO"
    UNKNOWN      = "UNKNOWN"


class MerchantCategory(str, Enum):
    ELECTRONICS      = "ELECTRONICS"
    APPAREL          = "APPAREL"
    DIGITAL_GOODS    = "DIGITAL_GOODS"
    TRAVEL           = "TRAVEL"
    GROCERY          = "GROCERY"
    GAMING           = "GAMING"
    FINANCIAL        = "FINANCIAL"
    MARKETPLACE      = "MARKETPLACE"
    UNKNOWN          = "UNKNOWN"


class DataSource(str, Enum):
    """Tracks where this record originated — for lineage and debugging."""
    SYNTHETIC   = "SYNTHETIC"   # Generated by SyntheticDataGenerator.java
    IEEE_CIS    = "IEEE_CIS"    # IEEE-CIS Fraud Detection benchmark dataset
    CSV_UPLOAD  = "CSV_UPLOAD"  # Future: merchant CSV upload endpoint
    API_EVENT   = "API_EVENT"   # Future: real-time payment event API


# ---------------------------------------------------------------------------
# Core canonical transaction
# ---------------------------------------------------------------------------

class RawTransaction(BaseModel):
    """
    Canonical transaction representation.

    SOURCE FIELDS — populated directly from the ingestion layer.
    DERIVED FIELDS — computed later; not present in raw ingestion.
    SYNTHETIC FIELDS — filled with sensible defaults when the source
                       dataset doesn't provide a value; always documented.

    Rule: no field silently coerces a missing value to a false non-null.
    If a field is absent, it remains None.  Feature engineering handles
    None explicitly (usually imputes with a safe constant and adds an
    indicator feature).
    """

    # ── Identifiers (SOURCE) ────────────────────────────────────────────
    transaction_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique transaction identifier. Generated if absent.",
    )
    merchant_id: str = Field(
        description="Merchant tenant identifier. Required for multi-tenancy."
    )
    customer_id: str = Field(
        description="Customer identifier within this merchant's namespace."
    )

    # ── Timestamps (SOURCE) ─────────────────────────────────────────────
    timestamp: datetime = Field(
        description=(
            "Transaction event time. Used as the anchor for all "
            "historical feature windows — never include data from "
            "timestamps strictly after this value."
        )
    )

    # ── Financial (SOURCE) ──────────────────────────────────────────────
    amount: float = Field(
        gt=0,
        description="Transaction amount in the transaction currency.",
    )
    currency: str = Field(
        default="USD",
        min_length=3,
        max_length=3,
        description="ISO 4217 currency code.",
    )

    # ── Payment method (SOURCE) ─────────────────────────────────────────
    payment_method: PaymentMethod = Field(
        default=PaymentMethod.UNKNOWN,
        description="Payment instrument type.",
    )

    # ── Device / network (SOURCE) ───────────────────────────────────────
    device_id: Optional[str] = Field(
        default=None,
        description="Device fingerprint. None if not captured.",
    )
    ip_address: Optional[str] = Field(
        default=None,
        description="IPv4 or IPv6 address. None if not captured.",
    )

    # ── Geography (SOURCE) ──────────────────────────────────────────────
    billing_country: Optional[str] = Field(
        default=None,
        max_length=2,
        description="ISO 3166-1 alpha-2 billing country.",
    )
    shipping_country: Optional[str] = Field(
        default=None,
        max_length=2,
        description="ISO 3166-1 alpha-2 shipping country. None for digital goods.",
    )

    # ── Merchant context (SOURCE / SYNTHETIC) ───────────────────────────
    merchant_category: MerchantCategory = Field(
        default=MerchantCategory.UNKNOWN,
        description=(
            "Merchant category code grouping. "
            "SYNTHETIC: defaulted to UNKNOWN when not supplied by source."
        ),
    )

    # ── Email (SOURCE) ───────────────────────────────────────────────────
    email_domain: Optional[str] = Field(
        default=None,
        description="Domain part of customer email (e.g. 'gmail.com'). PII-free.",
    )

    # ── Refund information (SOURCE) ─────────────────────────────────────
    # IMPORTANT: refund fields represent information known AT prediction time.
    # A refund that occurs AFTER the transaction must not appear here.
    # At real-time scoring, is_refunded = False (refund hasn't happened yet).
    # For batch historical analysis, is_refunded may be True.
    # The feature pipeline must not use is_refunded as a predictive feature
    # (it is a post-transaction outcome, not a predictor).
    is_refunded: bool = Field(
        default=False,
        description=(
            "Whether this transaction was refunded. "
            "LEAKAGE WARNING: never use as a predictive feature — "
            "it is a post-transaction outcome, not available at decision time."
        ),
    )
    refund_amount: Optional[float] = Field(
        default=None,
        description="Refund amount if is_refunded=True.",
    )

    # ── Ground truth label (SOURCE — evaluation only) ───────────────────
    # CRITICAL: this field must NEVER enter the feature matrix.
    # It is preserved only so evaluation code can compare predictions to truth.
    is_fraud: Optional[bool] = Field(
        default=None,
        description=(
            "Ground truth fraud label. "
            "LEAKAGE WARNING: NEVER include in feature engineering. "
            "For evaluation use only."
        ),
    )

    # ── Data provenance (DERIVED) ────────────────────────────────────────
    data_source: DataSource = Field(
        default=DataSource.SYNTHETIC,
        description="Origin of this record for lineage tracking.",
    )

    # ── Validation ───────────────────────────────────────────────────────
    @field_validator("currency")
    @classmethod
    def currency_uppercase(cls, v: str) -> str:
        return v.upper().strip()

    @field_validator("billing_country", "shipping_country", mode="before")
    @classmethod
    def country_uppercase(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        v = v.upper().strip()
        return v if len(v) == 2 else None

    @field_validator("amount")
    @classmethod
    def amount_positive(cls, v: float) -> float:
        if v <= 0:
            raise ValueError(f"amount must be > 0, got {v}")
        return v

    @model_validator(mode="after")
    def refund_consistency(self) -> "RawTransaction":
        if self.is_refunded and self.refund_amount is None:
            # Tolerate: refund amount can legitimately be absent in some datasets
            pass
        if not self.is_refunded and self.refund_amount is not None:
            # Normalise: clear refund_amount if transaction not marked as refunded
            self.refund_amount = None
        return self

    model_config = {"use_enum_values": True}


# ---------------------------------------------------------------------------
# Customer context
# ---------------------------------------------------------------------------

class CustomerContext(BaseModel):
    """
    Per-customer context provided alongside transactions for feature computation.

    This contains aggregate customer history computed from transactions
    STRICTLY BEFORE the prediction window.  The feature pipeline receives
    both RawTransaction and CustomerContext; it must not compute statistics
    that extend beyond transaction.timestamp.
    """

    customer_id: str
    merchant_id: str

    # Account metadata
    account_age_days: Optional[int] = Field(
        default=None,
        ge=0,
        description="Days since account creation as of the prediction timestamp.",
    )

    # Historical aggregates — all computed from data BEFORE prediction time
    # (the caller is responsible for enforcing this; unit tests verify it)
    historical_transaction_count: int = Field(
        default=0,
        ge=0,
        description="Total transactions strictly before the prediction timestamp.",
    )
    historical_total_amount: float = Field(
        default=0.0,
        ge=0,
        description="Sum of transaction amounts strictly before the prediction timestamp.",
    )
    historical_refund_count: int = Field(
        default=0,
        ge=0,
        description="Refund count strictly before the prediction timestamp.",
    )
    historical_device_count: int = Field(
        default=0,
        ge=0,
        description="Distinct devices used strictly before the prediction timestamp.",
    )
    historical_ip_count: int = Field(
        default=0,
        ge=0,
        description="Distinct IPs used strictly before the prediction timestamp.",
    )

    # Historical fraud rate — ONLY from previously labeled transactions,
    # never including the current transaction or any future labels.
    historical_fraud_rate: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description=(
            "Fraction of prior transactions labeled as fraud, "
            "computed only from transactions strictly before the prediction timestamp. "
            "None if no prior labeled history is available."
        ),
    )


# ---------------------------------------------------------------------------
# Data quality record
# ---------------------------------------------------------------------------

class DataQualityStats(BaseModel):
    """
    Summary statistics produced by the data quality pipeline for every
    dataset run.  Stored alongside the feature data for auditability.
    Never silently discard rejected records — track them here.
    """

    rows_received: int = 0
    rows_accepted: int = 0
    rows_rejected: int = 0
    duplicate_rows: int = 0
    missing_transaction_id: int = 0
    missing_customer_id: int = 0
    missing_merchant_id: int = 0
    missing_timestamp: int = 0
    invalid_timestamp: int = 0
    future_timestamp: int = 0
    missing_amount: int = 0
    invalid_amount: int = 0       # zero, negative, or non-numeric
    amount_extreme_high: int = 0  # above configurable ceiling (default $1M)
    missing_currency: int = 0
    invalid_currency: int = 0
    rejection_reasons: list[str] = Field(default_factory=list)

    @property
    def acceptance_rate(self) -> float:
        if self.rows_received == 0:
            return 0.0
        return self.rows_accepted / self.rows_received

    @property
    def rejection_rate(self) -> float:
        return 1.0 - self.acceptance_rate

    def summary(self) -> dict:
        return {
            "rows_received":     self.rows_received,
            "rows_accepted":     self.rows_accepted,
            "rows_rejected":     self.rows_rejected,
            "acceptance_rate":   round(self.acceptance_rate, 4),
            "duplicate_rows":    self.duplicate_rows,
            "missing_critical":  (
                self.missing_transaction_id
                + self.missing_customer_id
                + self.missing_merchant_id
                + self.missing_timestamp
                + self.missing_amount
            ),
            "invalid_amounts":   self.invalid_amount,
            "invalid_timestamps": self.invalid_timestamp + self.future_timestamp,
        }
