package com.zeno.api.resolution;

public enum ActionType {
    REQUEST_PROVIDER_REVIEW,
    REQUEST_MISSING_INFORMATION,
    CONTACT_PHARMACY,
    VERIFY_INSURANCE,
    REQUEST_NEW_PRESCRIPTION,
    REQUEST_PROVIDER_APPROVAL,
    FOLLOW_UP_WITH_PRACTICE,
    VERIFY_RESOLUTION,
    ESCALATE_CASE,
    CONTACT_PATIENT,
    PRIOR_AUTH_REQUEST,
    OTHER
}
