spring:
  jpa:
    show-sql: true

logging:
  level:
    com.zeno: DEBUG
    org.springframework.security: INFO
    org.flywaydb: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
